version: "3.9"

services:
  busybee_api:
    image: loldc1/busybee.api
    container_name: busybee.api
    restart: always
    volumes:
      - /var/www/images:/app/images
      - /var/www/files:/app/files
    depends_on:
      - postgres_db
    env_file:
      - ./config_api.env
    ports:
      - "127.0.0.1:8001:80"

  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./config_db.env
    ports:
      - "5432:5432"