// <auto-generated />
using System;
using BusyBee.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusyBee.Persistence.Design.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230311152109_EditCategoryOfTasks")]
    partial class EditCategoryOfTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfCategories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CategoriesOfCategories");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfTasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderAddressDataTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentDataTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderAddressDataTemplateId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PaymentDataTemplateId");

                    b.ToTable("CategoriesOfTasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DataTemplates");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataTemplateId");

                    b.ToTable("DataTemplateItems");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItemValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AddedMoney")
                        .HasColumnType("integer");

                    b.Property<Guid>("DataTemplateItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataTemplateItemId");

                    b.ToTable("DataTemplateItemValues");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfidentialInfo")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataTemplateItemValue", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateItemValueId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "DataTemplateItemId", "DataTemplateItemValueId");

                    b.HasIndex("DataTemplateItemId");

                    b.HasIndex("DataTemplateItemValueId");

                    b.ToTable("TaskDataTemplateItemValues");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataValue", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskId", "DataTemplateItemId");

                    b.HasIndex("DataTemplateItemId");

                    b.ToTable("TaskDataValues");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfCategories", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.CategoryOfCategories", "Parent")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfTasks", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplate", "OrderAddressDataTemplate")
                        .WithMany()
                        .HasForeignKey("OrderAddressDataTemplateId");

                    b.HasOne("BusyBee.Core.Entities.CategoryOfCategories", "Parent")
                        .WithMany("CategoriesOfTasks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BusyBee.Core.Entities.DataTemplate", "PaymentDataTemplate")
                        .WithMany()
                        .HasForeignKey("PaymentDataTemplateId");

                    b.Navigation("OrderAddressDataTemplate");

                    b.Navigation("Parent");

                    b.Navigation("PaymentDataTemplate");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItem", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplate", "DataTemplate")
                        .WithMany("DataTemplateItems")
                        .HasForeignKey("DataTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplate");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItemValue", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplateItem", "DataTemplateItem")
                        .WithMany("DataTemplateAdditional")
                        .HasForeignKey("DataTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplateItem");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.Task", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.CategoryOfTasks", "CategoryOfTasks")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryOfTasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataTemplateItemValue", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplateItem", "DataTemplateItem")
                        .WithMany()
                        .HasForeignKey("DataTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusyBee.Core.Entities.DataTemplateItemValue", "DataTemplateItemValue")
                        .WithMany()
                        .HasForeignKey("DataTemplateItemValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusyBee.Core.Entities.Task", "Task")
                        .WithMany("TaskDataTemplateItemValues")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplateItem");

                    b.Navigation("DataTemplateItemValue");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataValue", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplateItem", "DataTemplateItem")
                        .WithMany()
                        .HasForeignKey("DataTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusyBee.Core.Entities.Task", "Task")
                        .WithMany("TaskDataValues")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplateItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfCategories", b =>
                {
                    b.Navigation("CategoriesOfTasks");

                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfTasks", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplate", b =>
                {
                    b.Navigation("DataTemplateItems");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItem", b =>
                {
                    b.Navigation("DataTemplateAdditional");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.Task", b =>
                {
                    b.Navigation("TaskDataTemplateItemValues");

                    b.Navigation("TaskDataValues");
                });
#pragma warning restore 612, 618
        }
    }
}
