// <auto-generated />
using System;
using BusyBee.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusyBee.Persistence.Design.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230514115910_AddIconfilenameinCategories")]
    partial class AddIconfilenameinCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfCategories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconFilename")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CategoriesOfCategories");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfTasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconFilename")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderAddressDataTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentDataTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderAddressDataTemplateId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PaymentDataTemplateId");

                    b.ToTable("CategoriesOfTasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DataTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd081f14-3b0d-4d49-9aea-d3cb1fe379d8")
                        },
                        new
                        {
                            Id = new Guid("7cfc38e6-97fc-41d6-a267-0e160c2d2fba")
                        });
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataTemplateId");

                    b.ToTable("DataTemplateItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90883a11-4a54-4c3e-b574-4b1d033c391d"),
                            DataTemplateId = new Guid("cd081f14-3b0d-4d49-9aea-d3cb1fe379d8"),
                            Title = "Адрес",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("0d6701ca-8e30-4105-a9f8-6485b02eaffa"),
                            DataTemplateId = new Guid("7cfc38e6-97fc-41d6-a267-0e160c2d2fba"),
                            Title = "От",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("1f7dcab2-0c35-47c5-b433-f2334c1ede08"),
                            DataTemplateId = new Guid("7cfc38e6-97fc-41d6-a267-0e160c2d2fba"),
                            Title = "До",
                            Type = 0
                        });
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItemValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AddedMoney")
                        .HasColumnType("integer");

                    b.Property<Guid>("DataTemplateItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataTemplateItemId");

                    b.ToTable("DataTemplateItemValues");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfidentialInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataTemplateItemValue", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateItemValueId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "DataTemplateItemId", "DataTemplateItemValueId");

                    b.HasIndex("DataTemplateItemId");

                    b.HasIndex("DataTemplateItemValueId");

                    b.ToTable("TaskDataTemplateItemValues");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataValue", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataTemplateItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskId", "DataTemplateItemId");

                    b.HasIndex("DataTemplateItemId");

                    b.ToTable("TaskDataValues");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfCategories", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.CategoryOfCategories", "Parent")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfTasks", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplate", "OrderAddressDataTemplate")
                        .WithMany()
                        .HasForeignKey("OrderAddressDataTemplateId");

                    b.HasOne("BusyBee.Core.Entities.CategoryOfCategories", "Parent")
                        .WithMany("CategoriesOfTasks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BusyBee.Core.Entities.DataTemplate", "PaymentDataTemplate")
                        .WithMany()
                        .HasForeignKey("PaymentDataTemplateId");

                    b.Navigation("OrderAddressDataTemplate");

                    b.Navigation("Parent");

                    b.Navigation("PaymentDataTemplate");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItem", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplate", "DataTemplate")
                        .WithMany("DataTemplateItems")
                        .HasForeignKey("DataTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplate");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItemValue", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplateItem", "DataTemplateItem")
                        .WithMany("DataTemplateAdditional")
                        .HasForeignKey("DataTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplateItem");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.Task", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.CategoryOfTasks", "CategoryOfTasks")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryOfTasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataTemplateItemValue", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplateItem", "DataTemplateItem")
                        .WithMany()
                        .HasForeignKey("DataTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusyBee.Core.Entities.DataTemplateItemValue", "DataTemplateItemValue")
                        .WithMany()
                        .HasForeignKey("DataTemplateItemValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusyBee.Core.Entities.Task", "Task")
                        .WithMany("TaskDataTemplateItemValues")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplateItem");

                    b.Navigation("DataTemplateItemValue");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.TaskDataValue", b =>
                {
                    b.HasOne("BusyBee.Core.Entities.DataTemplateItem", "DataTemplateItem")
                        .WithMany()
                        .HasForeignKey("DataTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusyBee.Core.Entities.Task", "Task")
                        .WithMany("TaskDataValues")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTemplateItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfCategories", b =>
                {
                    b.Navigation("CategoriesOfTasks");

                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.CategoryOfTasks", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplate", b =>
                {
                    b.Navigation("DataTemplateItems");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.DataTemplateItem", b =>
                {
                    b.Navigation("DataTemplateAdditional");
                });

            modelBuilder.Entity("BusyBee.Core.Entities.Task", b =>
                {
                    b.Navigation("TaskDataTemplateItemValues");

                    b.Navigation("TaskDataValues");
                });
#pragma warning restore 612, 618
        }
    }
}
